---
- hosts: localhost
  connection: local

  tasks:
    - name: start an instance with a public IP address
      amazon.aws.ec2_instance:
        name: "{{ item.name }}"
        key_name: "manage-nodes"
        instance_type: t2.micro
        security_group: default
        region: us-east-1
        aws_access_key: "{{ ec2_access_key }}"
        aws_secret_key: "{{ ec2_secret_key }}"
        network_interfaces:
          - assign_public_ip: true
        image_id: "{{ item.image }}"
        tags:
          Environment: Testing
      loop:
        - { image: "ami-0150ccaf51ab55a51", name: "ansible-instance-1" }
        - { image: "ami-0150ccaf51ab55a51", name: "ansible-instance-2" }
        - { image: "ami-020cba7c55df1f615", name: "ansible-instance-3" }