---
- hosts: all
  become: true

  tasks:
    # - name: for debug
    #   ansible.builtin.debug:
    #     var: ansible_facts['os_family']

    - name: stop an instance
      ansible.builtin.command: /sbin/shutdown -t now
      when: ansible_facts['os_family'] == 'Debian'
        
     

 